server:
  port: 8080

spring:
    datasource:
        name: dev
        url: jdbc:mysql://192.168.1.134:3306/dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: 123456
        #druid datasource
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 200
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        filters: stat,wall,log4j2
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true

    redis:
        database: 1
        host: 192.168.1.136
        port: 6379
        password: 123456
        timeout: 10000
        jedis:
            pool:
              max-active: 1000
              max-wait: -1
              max-idle: 1000
              min-idle: 0

    aop:
      auto: true
      proxy-target-class: false

    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

swagger:
  title: entity-gcyl
  description: 实体
  version: 1.1.0.RELEASE
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  contact.name: lican
  contact.email: afmrlii@163.com
  base-package: gcyl.entity.controller
  base-path: /**
  exclude-path: /error, /ops/**

#  paging plugin
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


#mybatis:
#  mapper-locations: classpath*:gcyl.entity.domain.mapper/*.xml
#  type-aliases-package: gcyl.entity.domain.model