package gcyl.entity.domain.mapper;

import gcyl.entity.domain.model.QrCode;
import gcyl.entity.domain.model.QrCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    int countByExample(QrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    int deleteByExample(QrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    int insert(QrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    int insertSelective(QrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    List<QrCode> selectByExample(QrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    QrCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") QrCode record, @Param("example") QrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    int updateByExample(@Param("record") QrCode record, @Param("example") QrCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    int updateByPrimaryKeySelective(QrCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tyg_ms_qr_code
     *
     * @mbggenerated Fri Jan 18 10:29:56 CST 2019
     */
    int updateByPrimaryKey(QrCode record);
}